// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using clinicaDocMais.Data;

#nullable disable

namespace clinicaDocMais.Migrations
{
    [DbContext(typeof(ClinicaContext))]
    [Migration("20260423170303_inicio")]
    partial class inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("clinicaDocMais.Models.AgendamentoModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Cpf")
                        .HasColumnType("longtext");

                    b.Property<string>("Crm")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataHoraAtendimento")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("PresencaConfirmada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<string>("especialidadeMedico")
                        .HasColumnType("longtext");

                    b.Property<string>("nomeMedico")
                        .HasColumnType("longtext");

                    b.Property<string>("nomePaciente")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("agendamentos");
                });

            modelBuilder.Entity("clinicaDocMais.Models.ChamadaModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ChamadaModelid")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("HoraChamada")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrdemChamada")
                        .HasColumnType("int");

                    b.Property<string>("PacienteNome")
                        .HasColumnType("longtext");

                    b.Property<string>("SalaMedico")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("ChamadaModelid");

                    b.ToTable("chamadas");
                });

            modelBuilder.Entity("clinicaDocMais.Models.MedicoModel", b =>
                {
                    b.Property<string>("crm")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("endereco")
                        .HasColumnType("longtext");

                    b.Property<string>("especialidade")
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .HasColumnType("longtext");

                    b.Property<string>("telefone")
                        .HasColumnType("longtext");

                    b.HasKey("crm");

                    b.ToTable("medicos");
                });

            modelBuilder.Entity("clinicaDocMais.Models.PacienteModels", b =>
                {
                    b.Property<string>("cpf")
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("dataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .HasColumnType("longtext");

                    b.Property<string>("telefone")
                        .HasColumnType("longtext");

                    b.HasKey("cpf");

                    b.ToTable("pacientes");
                });

            modelBuilder.Entity("clinicaDocMais.Models.ChamadaModel", b =>
                {
                    b.HasOne("clinicaDocMais.Models.ChamadaModel", null)
                        .WithMany("Chamadas")
                        .HasForeignKey("ChamadaModelid");
                });

            modelBuilder.Entity("clinicaDocMais.Models.ChamadaModel", b =>
                {
                    b.Navigation("Chamadas");
                });
#pragma warning restore 612, 618
        }
    }
}
